var CANVAS_WIDTH = 968;
var CANVAS_HEIGHT = 1224;

var EDGEBOARD_X = 100;
var EDGEBOARD_Y = 100;

var DISABLE_SOUND_MOBILE = false;
var FONT_GAME = "space_marinenominal";

var FPS_TIME      = 1000/24;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;


var HERO_START_X = CANVAS_WIDTH/2;
var HERO_ACCELLERATION;
var HERO_FRICTION;
var MAX_HERO_SPEED;
var START_Y_FALLING_OBJ = -50;
var TIME_OCCURENCE_FALLING_OBJ;
var SPEED_FALLING_OBJ;
var MAX_SPEED_FALLING_OBJ;
var NUM_FALLING_OBJ = 4;
var NUM_LIVES;
var SPEED_PLAYER_BULLET;
var SCORE_HIT;
var PARALLAX1_SPEED = 1;
var PARALLAX2_SPEED = 10;
var MIN_SHOT_OCCURENCE;
var MAX_SHOT_OCCURENCE;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;